apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-backend
  labels:
    app: devops-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: devops-backend
  template:
    metadata:
      labels:
        app: devops-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.backend.servicePort }}
          env:
            {{- range $key, $value := .Values.backend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
