apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend
  labels:
    app: devops-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.frontend.servicePort }}
